### ISSUE TITLE
Not working on newer A9LH

### ISSUE THREAD

**Issue by dogtopus** [Wolfvak/FakeBrick9#2]
When I upgrade my A9LH to the latest version (delebile/arm9loaderhax@ae297e8) and boot FakeBrick9, I got a legit black screen.
On older A9LH it worked fine.

**Comment by Wolfvak** [comment]
I'll check it out, but consider it low priority.
In the meantime, can you test all previous releases and get back at me?

**Comment by Wolfvak** [comment]
Probably fixed with https://github.com/Wolfvak/FakeBrick9/commit/49767a112d0f42bd94908170c798fb5c946509df
